# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
